FORMAT: 1A
HOST: http://www.google.com

# svobodni
## Správa uživatelů
Metody slouží pro administraci uživatelů a pro další úlohy oprávněným uživatelům a systémům.

# Profile [/json/profile-load.php]
Editace vlastního profilu
V případě profilu se nepoužívá ID, je dané identitou přihlášeného uživatele.

### Retrieve profile [GET]
+ Response 200 (application/json)

    + Body

            {"id":"455","titul1":"Ing.","titul2":null,"jmeno":"Ji\u0159\u00ed","prijmeni":"Kub\u00ed\u010dek"}
