FORMAT: 1A
HOST: http://www.google.com

# svobodni
## Správa uživatelů
Metody slouží pro administraci uživatelů a pro další úlohy oprávněným uživatelům a systémům.

## User [/api/users/{id}]
+ Model (application/json)
  
    + Body

            {
                "id":"999",
                "openid":"lampa@svobodni.cz",
                "titul1":"Ing.",
                "titul2":null,
                "jmeno":"Jan",
                "prijmeni":"Lampa",
                "email":"lampa@svobodni.cz",
                "vs":"10999",
                "narozeni":"1970-02-18 00:00:00",
                "rodnecislo":"700218\/1234",
                "povolani":null,
                "poznamka":null,
                "adresatxt":"",
                "kontaktgeneral":[
                  {
                    "typ":"phone",
                    "obsah":"123456789",
                    "status":"1"
                  },
                  {
                    "typ":"homepage",
                    "obsah":"www.lampa.cz",
                    "status":null
                  },
                  {
                    "typ":"fbProfile",
                    "obsah":"http:\/\/www.facebook.com\/lampa",
                    "status":null
                  },
                  {
                    "typ":"fbPage",
                    "obsah":"http:\/\/www.facebook.com\/lampa-politik",
                    "status":null
                  }
                ],
                "kontaktadresa":[
                ],
                "clen":{
                  "exclen":"v \u017e\u00e1dn\u00e9",
                  "exkand":null,
                  "status":"100",
                  "zacatek":"1357772400",
                  "konec":null
                },
                "priznivec":null,
                "clenstvi":[
                  {
                    "druh":"1",
                    "organizace":"5",
                    "adresa":{
                      "mistni":null,
                      "ulice":"Stromovka 126",
                      "mesto":"Praha 7",
                      "psc":"17000",
                      "stat":"\u010cesk\u00e1 republika",
                      "geolat":null,
                      "geolong":null
                    }
                  }
                ],
                "prispevek":[
                ],
                "mandat":[
                ],
                "funkcionar":[
                  {
                    "vznik":"1345672800",
                    "zanik":"1408744800",
                    "organ":"2",
                    "funkce":"1"
                  }
                ]
            }

### Detail uživatele [GET]
Vrací jeden záznam ze seznamu uživatelů ve struktuře user. 

+ Parameters
    + id (required, number, `1001`) ... Id uživatele.

+ Response 200

    [User][]


## Organizace [/api/organizace]
Organizační jednotky (kraje, pobočky)

### Seznam organizací [GET]
+ Response 200 (application/json)

    + Body

            [{"id":"4","nadrazena":null,"druh":null,"nazev":"Zlínský kraj","oldkraj":"14"}, {"id":"5","nadrazena":null,"druh":null,"nazev":"Praha","oldkraj":"10"}]

