FORMAT: 1A
HOST: http://www.google.com

# svobodni
## Správa uživatelů
Metody slouží pro administraci uživatelů a pro další úlohy oprávněným uživatelům a systémům.

# User [/json/user-load.php?id=1]
+ Model (application/json)
  
    + Body

            {
                "id":"1",
                "openid":"novak",
                "jmeno":"Jan",
                "prijmeni":"Novák",
                "titul1":"Ing.",
                "titul2":"CSc.",
                "email":"novak@somemail.com"
            }
    + Schema
    
            {
                "type":"object",
                "properties":{
                "id": {
                    "type":"string",
                },
                "openid": {
                    "type":"string",
                    "description": "neměnný OpenID identifikátor, tvoří se z prvního uživatele",
                },
                "jmeno": {
                    "type":"string",
                    "description": "křestní jméno"
                },
                "prijmeni": {
                    "type":"string",
                    "description": "příjmení"
                },
                "titul1": {
                    "type":"string",
                    "description": "titul(y) před jménem"
                },
                "titul2": {
                    "type":"string",
                    "description": "titul(y) za jménem"
                },
                "email": {
                    "type":"string",
                    "description":"e-mail"
                }
            }

### Retrieve metoda oiuser-load [GET]
Vrací jeden záznam ze seznamu uživatelů ve struktuře user. Oprávněný uživatel má přístup ke generované přihlášce člena na url /reg/reg-ID.pdf

+ Parameters
    + id (required, number, `1001`) ... Id uživatele.

+ Response 200

    [User][]

# Profile [/json/profile-load.php]
Editace vlastního profilu

V případě profilu se nepoužívá ID, je dané identitou přihlášeného uživatele.

### Retrieve profile [GET]
+ Response 200 (application/json)

    + Body

            {"id":"455","titul1":"Ing.","titul2":null,"jmeno":"Ji\u0159\u00ed","prijmeni":"Kub\u00ed\u010dek"}
